AspNetCoreMvc-WithAPI/Models/CityViewModel.cs
namespace AspNetCoreMvc_WithAPI.Models
{
	public class CityViewModel
	{
		public int Id { get; set; }
		public string Name { get; set; }
		public string Region { get; set; }
		public string Code { get; set; }
	}
}

AspNetCoreMvc-WithAPI/Models/ErrorViewModel.cs
namespace AspNetCoreMvc_WithAPI.Models
{
	public class ErrorViewModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

AspNetCoreMvc-WithAPI/Controllers/CityController.cs
using AspNetCoreMvc_WithAPI.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Text;
using System.Text.Json.Serialization;

namespace AspNetCoreMvc_WithAPI.Controllers
{
	public class CityController : Controller
	{
		private readonly IHttpClientFactory _httpClientFactory;
		public CityController(IHttpClientFactory httpClientFactory)
		{
			_httpClientFactory = httpClientFactory;
		}
		public async Task<IActionResult> Index()
		{
			var http = _httpClientFactory.CreateClient(); //HttpClient nesnesi oluşur.
			var result = await http.GetAsync("https://localhost:7136/api/Cities");
			if(result.IsSuccessStatusCode)
			{
				var jsonData = await result.Content.ReadAsStringAsync();
				var data = JsonConvert.DeserializeObject<List<CityViewModel>>(jsonData); //Json Serialize işlemleri için Newtonsoft.Json paketini projemize yüklüyoruz.
				return View(data);
			}
			return View();
		}
		public IActionResult Create()
		{
			return View();
		}
		[HttpPost]
		public async Task<IActionResult> Create(CityViewModel model)
		{
			var http = _httpClientFactory.CreateClient();
			var jsonData = JsonConvert.SerializeObject(model);  //view'dan gelen datayı json formata serialize ediyoruz.
			var content = new StringContent(jsonData, encoding: Encoding.UTF8, "application/json");
			var result = await http.PostAsync("https://localhost:7136/api/Cities", content);
			if(result.IsSuccessStatusCode)
			{
				return RedirectToAction("Index");
			}
			return View();
		}
		[HttpGet]
		public async Task<IActionResult> Edit(int id)
		{
			var http = _httpClientFactory.CreateClient();
			//gelen id'ye sahip City bilgisi API'den çekilecek.
			var result = await http.GetAsync($"https://localhost:7136/api/Cities/{id}");
			if (result.IsSuccessStatusCode)
			{
				var jsonData = await result.Content.ReadAsStringAsync();
				var data = JsonConvert.DeserializeObject<CityViewModel>(jsonData);
				return View(data);
			}
			return View();
		}
		[HttpPost]
		public async Task<IActionResult> Edit(CityViewModel model)
		{
			var http = _httpClientFactory.CreateClient();
			var jsonData = JsonConvert.SerializeObject(model);
			var content = new StringContent(jsonData, encoding: Encoding.UTF8, "application/json");
			var result = await http.PutAsync("https://localhost:7136/api/Cities", content);
			if (result.IsSuccessStatusCode)
			{
				return RedirectToAction("Index");
			}
			return View(model);
		}
		public async Task<IActionResult> Delete(int id) 
		{
			var http = _httpClientFactory.CreateClient();
			var result = await http.DeleteAsync($"https://localhost:7136/api/Cities/{id}");
			if (result.IsSuccessStatusCode)
			{
				return RedirectToAction("Index");
			}
			return View();
		}
	}
}

AspNetCoreMvc-WithAPI/Controllers/HomeController.cs
using AspNetCoreMvc_WithAPI.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AspNetCoreMvc_WithAPI.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

AspNetCoreMvc-WithAPI/Views/City/Create.cshtml
@model AspNetCoreMvc_WithAPI.Models.CityViewModel

@{
    ViewData["Title"] = "Create";
}

<h4>New City</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Region" class="control-label"></label>
                <input asp-for="Region" class="form-control" />
                <span asp-validation-for="Region" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Code" class="control-label"></label>
                <input asp-for="Code" class="form-control" />
                <span asp-validation-for="Code" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AspNetCoreMvc-WithAPI/Views/City/Edit.cshtml
@model AspNetCoreMvc_WithAPI.Models.CityViewModel

@{
    ViewData["Title"] = "Edit";
}

<h4>City Update</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" method="post">
            <input type="hidden" asp-for="Id" />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Region" class="control-label"></label>
                <input asp-for="Region" class="form-control" />
                <span asp-validation-for="Region" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Code" class="control-label"></label>
                <input asp-for="Code" class="form-control" />
                <span asp-validation-for="Code" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AspNetCoreMvc-WithAPI/Views/City/Index.cshtml
@model IEnumerable<AspNetCoreMvc_WithAPI.Models.CityViewModel>

@{
    ViewData["Title"] = "Index";
}

<p>
    <a asp-action="Create">Create New City</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Region)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Code)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Region)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Code)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.Id}) |
                <a asp-action="Delete" asp-route-id="@item.Id" onclick="return confirm('Silmek İstiyor musunuz?') ">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

AspNetCoreMvc-WithAPI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

AspNetCoreMvc-WithAPI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AspNetCoreMvc_WithAPI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AspNetCoreMvc_WithAPI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AspNetCoreMvc_WithAPI</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="City" asp-action="Index">City List</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - AspNetCoreMvc_WithAPI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>